name: Code quality

on: [push, pull_request]

jobs:

  lint:

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: lint code
      run: npm run lint

  test:

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use npm cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Test code
        run: npm run test

      - name: Generate coverage report
        run: npx tap --coverage-report=text-lcov > coverage.lcov

      - name: Report coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.lcov
